void bootMessage () {
  lcd.setCursor(0, 0);
  lcd.print("Electronic Video");
  lcd.setCursor(0, 1);
  lcd.print("Agent v2.0 beta");
   delay (3000);
  
  lcd.setCursor(0, 0);
  lcd.print("                ");
  lcd.setCursor(0, 1);
  lcd.print("                ");


  lcd.setCursor(0, 0);
  lcd.print(".");
delay (200);
lcd.setCursor(1, 0);
  lcd.print(".");
delay (200);
lcd.setCursor(2, 0);
  lcd.print(".");
delay (200);
lcd.setCursor(3, 0);
  lcd.print(".");
delay (200);
lcd.setCursor(4, 0);
  lcd.print(".");
  delay (200);
lcd.setCursor(5, 0);
  lcd.print(".");
  delay (200);
lcd.setCursor(6, 0);
  lcd.print(".");
    delay (200);
lcd.setCursor(7, 0);
  lcd.print(".");
    delay (200);
lcd.setCursor(8, 0);
  lcd.print(".");
    delay (200);
lcd.setCursor(9, 0);
  lcd.print(".");
    delay (200);
lcd.setCursor(10, 0);
  lcd.print(".");
     delay (2000);
lcd.setCursor(11, 0);
  lcd.print(".");
    delay (50);
lcd.setCursor(12, 0);
  lcd.print(".");
      delay (50);
lcd.setCursor(13, 0);
  lcd.print(".");
      delay (50);
lcd.setCursor(14, 0);
  lcd.print(".");
      delay (50);
lcd.setCursor(15, 0);
  lcd.print(".");
      delay (50);
lcd.setCursor(16, 0);
  lcd.print(".");
delay (50);


  lcd.setCursor(0, 1);
  lcd.print(".");
delay (50);
lcd.setCursor(1, 1);
  lcd.print(".");
delay (50);
lcd.setCursor(2, 1);
  lcd.print(".");
delay (50);
lcd.setCursor(3, 1);
  lcd.print(".");
delay (50);
lcd.setCursor(4, 1);
  lcd.print(".");
  delay (50);
lcd.setCursor(5, 1);
  lcd.print(".");
  delay (50);
lcd.setCursor(6, 1);
  lcd.print(".");
    delay (50);
lcd.setCursor(7, 1);
  lcd.print(".");
    delay (50);
lcd.setCursor(8, 1);
  lcd.print(".");
    delay (50);
lcd.setCursor(9, 1);
  lcd.print(".");
    delay (50);
lcd.setCursor(10, 1);
  lcd.print(".");
    delay (50);
lcd.setCursor(11, 1);
  lcd.print(".");
    delay (50);
lcd.setCursor(12, 1);
  lcd.print(".");
      delay (50);
lcd.setCursor(13, 1);
  lcd.print(".");
      delay (50);
lcd.setCursor(14, 1);
  lcd.print(".");
      delay (50);
lcd.setCursor(15, 1);
  lcd.print(".");
      delay (50);
lcd.setCursor(16, 1);
  lcd.print(".");
 delay (500);


  lcd.setCursor(0, 0);
  lcd.print("  WELCOME BACK  ");
  lcd.setCursor(0, 1);
  lcd.print("    COMMANDER   ");

  delay (5000);
  lcd.setCursor(0, 1);
  lcd.print("                ");
  lcd.setCursor(0, 0);
  lcd.print("                ");

}
